### ISSUE TITLE
What version of jmeter is needed?

### ISSUE THREAD

**Issue by igemon** [delirius325/jmeter-elasticsearch-backend-listener#34]
Hi!

I didn't find any information in the documents about lisener compatibility with jmeter versions. I tried using listener version 2.5.0 with jmeter 3.3 and jmeter 4.0 but it didn't work. 

But listener version 2.4.3 worked with jmeter 4.0. 
Do I understand correctly that the second digit in the listener version is the jmeter version?
Which version will work with jmeter 3.3?

Thanks!

**Comment by delirius325** [comment]
Hi @igemon,

You don't need a specific JMeter version. I'm using 2.5.0 on my JMeter 5.0 (and I had been using it on JMeter 4.0 before it released). Could you describe why you say it's not working with 2.5.0? 

It's important to note that there seems to be a problem with JMeter-Plugins registering version 2.5.0, despite it being declared here:

https://github.com/undera/jmeter-plugins/blob/master/site/dat/repo/various.json#L452-L459

Thanks,

**Comment by igemon** [comment]
Hi @delirius325.

I created TestPlan with some DummySamplers and jmeter-elasticsearch-backend-listener v2.5.0.
I try to start on jmeter 3.3 and get an error in log:
```
2018-09-26 16:37:10,926 ERROR o.a.j.JMeter: Uncaught exception: 
java.lang.NoSuchMethodError: org.elasticsearch.client.RestClient.performRequest(Lorg/elasticsearch/client/Request;)Lorg/elasticsearch/client/Response;
	at io.github.delirius325.jmeter.backendlistener.elasticsearch.ElasticSearchMetricSender.sendRequest(ElasticSearchMetricSender.java:96) ~[jmeter.backendlistener.elasticsearch-2.5.0.jar:?]
	at io.github.delirius325.jmeter.backendlistener.elasticsearch.ElasticsearchBackendClient.teardownTest(ElasticsearchBackendClient.java:139) ~[jmeter.backendlistener.elasticsearch-2.5.0.jar:?]
	at org.apache.jmeter.visualizers.backend.BackendListener.testEnded(BackendListener.java:395) ~[ApacheJMeter_components.jar:3.3 r1808647]
	at org.apache.jmeter.visualizers.backend.BackendListener.testEnded(BackendListener.java:405) ~[ApacheJMeter_components.jar:3.3 r1808647]
	at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfEnd(StandardJMeterEngine.java:230) ~[ApacheJMeter_core.jar:3.3 r1808647]
	at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:498) ~[ApacheJMeter_core.jar:3.3 r1808647]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
```
I try to start on jmeter 4.0 and get an error in log:
```
2018-09-26 16:45:26,618 ERROR o.a.j.JMeter: Uncaught exception: 
java.lang.NoSuchMethodError: org.elasticsearch.client.RestClient.performRequest(Lorg/elasticsearch/client/Request;)Lorg/elasticsearch/client/Response;
	at io.github.delirius325.jmeter.backendlistener.elasticsearch.ElasticSearchMetricSender.sendRequest(ElasticSearchMetricSender.java:96) ~[jmeter.backendlistener.elasticsearch-2.5.0.jar:?]
	at io.github.delirius325.jmeter.backendlistener.elasticsearch.ElasticsearchBackendClient.teardownTest(ElasticsearchBackendClient.java:139) ~[jmeter.backendlistener.elasticsearch-2.5.0.jar:?]
	at org.apache.jmeter.visualizers.backend.BackendListener.testEnded(BackendListener.java:387) ~[ApacheJMeter_components.jar:4.0 r1823414]
	at org.apache.jmeter.visualizers.backend.BackendListener.testEnded(BackendListener.java:395) ~[ApacheJMeter_components.jar:4.0 r1823414]
	at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfEnd(StandardJMeterEngine.java:227) ~[ApacheJMeter_core.jar:4.0 r1823414]
	at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:495) ~[ApacheJMeter_core.jar:4.0 r1823414]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
```
And only in jmeter 5.0 there are no errors in log and I can see index in elasticsearch.

**Comment by delirius325** [comment]
Hi @igemon ,

Would you happen to have multiple versions of the plugin in your lib/ext folder? At first glance, this looks like a conflicting JAR issue.

Thanks,

**Comment by igemon** [comment]
@delirius325 Thanks.
In my `lib/ext` there was only one version of the plugin - v2.5.0.
But I decided to check it and downloaded the pure jmeter 3.3 and 4.0, added the plugin v2.5.0 and everything is OK. This looks like a conflict with some other JAR.

Sorry, it is my bad.

**Comment by delirius325** [comment]
No worries, glad your problem is fixed 😄 !
